### ISSUE TITLE
Viewtypes

### ISSUE THREAD

**Issue by natsoj2** [123Venom/plugin.video.venom#48]
I'm totally new here so I apologize in advance if this isn't the proper venue for this issue.

I'm having some frustrations with "Viewtypes" only being remembered on the first page. I choose "Info Wall" in Tools/Viewtypes works fine but only on the first page. When going to subsequent pages it defaults to "List". If there is a simple solution to this, I'd love to know what it is.

Also, as an aside....... I would be cool to have a way inside Venom to know if your VPN is still connected. Maybe in settings as you are watching the stream.

Thanks for supporting Venom.

**Comment by 123Venom** [comment]
After testing it seems to only be happening to movies for me.  TVShows, Season, Episodes were fine.  Looked like a menu cacheing issue and not reading the new set view type so I added a sleep state and it cured it for movies.  Can you confirm movies only?

**Comment by natsoj2** [comment]
Yes it does appear to be only for movies. Sorry I didn't notice that. I usually just search for TV shoes so I never get off of page one for TV.  Thanks for addressing this.

**Comment by bjbca** [comment]
Its the skin... So here is what i found a while ago, for example i use estuary, something like venom will request a view type for a page and lets say it will ask for 55(wide List), the skin will load wide list for the first page, but when you choose next the skin loads what its default new page view is.. estuary uses 50(List) and thus the view type changes on you because when you choose next the request for a particular view type is not made, the skin default is loaded. Being kind of handy I made my own "Estuary 2" and coded its default view type as the one I prefer 55(Wide List) and thus I can choose next and the view never changes.. the catch is Im not about to start distributing any skins but there you have the explanation of what is happening. If you like estuary then reddit-reaper puts out skin.esturaymod and it has a lot of customizable settings and also sets the default view as 55(Wide List) I believe. And then if Venom feels like tackling the complication of making the movies, tvshows, seasons and episodes .py scripts request a particular view type for every 'Next' page request .... well thats up to him... thats my take on the issue... hope it was of some help ;)

**Comment by 123Venom** [comment]
Sorry @bjbca but that is not entirely accurate!  The default view type is written to the addons `views.db` file, as you set per the `set views` function.  When each page is loaded we read this addons `views.db` file for the set view mode and then set the Container view mode, which the skin in turn writes it to the kodi database `ViewModes6.db` file for the path loaded.   There is no need of modifying any such `Next' page for tvshows, seasons, and episodes modules.  The problem occurs in movies only and seems to be the skin does not have time to load and write the table entry.  With an added sleep state the data is consistently written to `ViewModes6.db` and cures the write problem.  During testing I kept DB Browser open to watch this write process to the database and with movies it was inconsistent until a simple one line sleep state was added, for a mere 1/2 sec.

<img width="889" alt="Views1" src="https://user-images.githubusercontent.com/46383815/79529437-a56c0600-803a-11ea-9131-bcbdbb49f669.PNG">
with a sleep state added entry 7&8 is consistently written and I retested from scratch 3 times.

<img width="880" alt="reset_views" src="https://user-images.githubusercontent.com/46383815/79529496-cc2a3c80-803a-11ea-96be-9bbaf47fa453.PNG">
`Reset views` option wipes out both databases.

<img width="890" alt="Views2" src="https://user-images.githubusercontent.com/46383815/79529512-da785880-803a-11ea-967f-3972576fec75.PNG">
Without the sleep state the next page write to database rarely happens and hence the wrong view mode is used. I should have seen item #5 write the next page but it failed to do so.

@bjbca if you don't believe me add `control.sleep(500)` right before the view mode is set in movies.py and then compare the database writes with and without that sleep state and tell me what you witness....consistently written with the sleep state ha?

The addon already attempts to set the Container view mode, even for the next page...it just fails to happen for movies on a consistent basis. Fixed without this so called `complication` you claim..lol

**Comment by bjbca** [comment]
Nice work @123Venom ;), way better than my back alley mechanics... lol

**Comment by 123Venom** [comment]
@natsoj2 let me know if that latest version I pushed fixed your views for movies and I'll close this.

**Comment by bjbca** [comment]
@123Venom, in V3.61, problem persists in movies (Estuary skin) so i took your advice "add control.sleep(500) right before the view mode is set in movies.py", the delay was too noticeable so i set it to (100) and the delay was not noticeable and the view worked properly, thank you again. Im looking forward to your next release ;)

**Comment by bjbca** [comment]
@123Venom oops I spoke too soon, control.sleep(100) has inconsistent results, control.sleep(200) seems optimal.

**Comment by 123Venom** [comment]
yep..those sleep state sometimes cures the slightest hiccup but you have to watch for inconsistencies till ya nail it.

**Comment by natsoj2** [comment]
In 3.6.2 Movie veiwtypes is working for me. Thanks
